version: "3.7"
services:
  # Database Services
  postgres:
    image: postgres:13-alpine
    command: "postgres -c config_file='/etc/postgresql/postgresql.conf'"
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2000000000
          mode: 0777
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - database
      - easypanel
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - POOL_MODE=${POOL_MODE}
      - ADMIN_USERS=${ADMIN_USERS}
      - MAX_CLIENT_CONN=${MAX_CLIENT_CONN}
    # labels:
    #   - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
    #   - "traefik.http.routers.portainer.entrypoints=https"
    #   - "traefik.http.routers.portainer.rule=Host(`dbbouncer.connectabil.com`) && PathPrefix(`/`)"
    #   - "traefik.http.routers.portainer.service=portainer-service"
    #   - "traefik.http.services.portainer-service.loadbalancer.server.port=5432"
    #   - "traefik.http.routers.portainer.tls=true"
    #   - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
    ports:
      - "8193:5432"
    depends_on:
      - postgres
    networks:
      - database
      - easypanel
    restart: unless-stopped

volumes:
  db-data:

networks:
  database:
  monitoring:
  easypanel:
    external: true
