scrape_configs:
  - job_name: pg-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          instance: 'postgres'
  - job_name: pgbouncer-exporter
    static_configs:
      - targets: ["pgbouncer-exporter:9127"]
        labels:
          instance: 'pgbouncer'
  - job_name: query-exporter
    static_configs:
      - targets: ["query-exporter:9560"]
        labels:
          instance: 'postgres'
